title: TDM Printing
url: "https://tdmprinting.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key: AIzaSyD2gvKhFwkvvqiFudnOiNzXrGqkDEItMFw
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: TDMPrinting - 3D Printing for Professionals

# Author details for the jekyll-seo-tag gem
author:
  name: Dan Lathan
  email: info@tdmprinting.com
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: TDM Printing
  #links:
  #  - https://github.com/CloudCannon/urban-jekyll-template

collections:
  staff_members:
    output: false
  projects:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"
  - "jekyll-sitemap"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
